'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class WinFormStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AVSIB.WinFormStrings", GetType(WinFormStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Aborted! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strAborted() As String
            Get
                Return ResourceManager.GetString("strAborted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Addressees in database:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strAddresseesInDatabase() As String
            Get
                Return ResourceManager.GetString("strAddresseesInDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strAll() As String
            Get
                Return ResourceManager.GetString("strAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Backup successfully restored ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strBackupRestore() As String
            Get
                Return ResourceManager.GetString("strBackupRestore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Backup successfully saved ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strBackupSave() As String
            Get
                Return ResourceManager.GetString("strBackupSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please enter the title of the Project you need the address-lists for ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strBroMissing() As String
            Get
                Return ResourceManager.GetString("strBroMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Warning! This will delete ALL data! are you sure you want to continue? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strCautionDelete() As String
            Get
                Return ResourceManager.GetString("strCautionDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please make sure you select each option one time only! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strChooseOnce() As String
            Get
                Return ResourceManager.GetString("strChooseOnce", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cities in database:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strCitiesInDatabase() As String
            Get
                Return ResourceManager.GetString("strCitiesInDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die This will exit the program. Are you sure? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strConf2Close() As String
            Get
                Return ResourceManager.GetString("strConf2Close", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die , Date:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strDate() As String
            Get
                Return ResourceManager.GetString("strDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dristrict-No.:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strDistrictNo() As String
            Get
                Return ResourceManager.GetString("strDistrictNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  districts in the database. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strDistrictsInDatabase() As String
            Get
                Return ResourceManager.GetString("strDistrictsInDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You have reached the end of the database ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strEndDatabase() As String
            Get
                Return ResourceManager.GetString("strEndDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please fill in ALL fields ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strFieldsMissing() As String
            Get
                Return ResourceManager.GetString("strFieldsMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die It seems the file you have chosen does not exist. Make sure you have not moved or renamed the file. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strFileDoesntExist() As String
            Get
                Return ResourceManager.GetString("strFileDoesntExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die There already exists a file at this path. Going on will overwrite the old file. Continue? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strFileExists() As String
            Get
                Return ResourceManager.GetString("strFileExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please enter a city! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strInsertCity() As String
            Get
                Return ResourceManager.GetString("strInsertCity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please enter the house-number! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strInsertHouseNumber() As String
            Get
                Return ResourceManager.GetString("strInsertHouseNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please enter a street! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strInsertStreet() As String
            Get
                Return ResourceManager.GetString("strInsertStreet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please enter a ZIP-code! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strInsertZIP() As String
            Get
                Return ResourceManager.GetString("strInsertZIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strNew() As String
            Get
                Return ResourceManager.GetString("strNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You have not selected a backup to delete. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strNoBackupDelete() As String
            Get
                Return ResourceManager.GetString("strNoBackupDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No Backups found. Create one first. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strNoBackupsFound() As String
            Get
                Return ResourceManager.GetString("strNoBackupsFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You have not selected a backup to restore. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strNoBackupsSelected() As String
            Get
                Return ResourceManager.GetString("strNoBackupsSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No Cities found in database. Please enter the cities first. Go to Main Menu -&gt; Cities ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strNoCities() As String
            Get
                Return ResourceManager.GetString("strNoCities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please choose a city! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strNoCitySelected() As String
            Get
                Return ResourceManager.GetString("strNoCitySelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die There is no data in the database, yet ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strNoData() As String
            Get
                Return ResourceManager.GetString("strNoData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please choose a district ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strNoDestrictNo() As String
            Get
                Return ResourceManager.GetString("strNoDestrictNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die It seems you have not added a district yet. Please fill the database first before printing! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strNoDistrict() As String
            Get
                Return ResourceManager.GetString("strNoDistrict", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No data matches the selected filter. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strNoFilterData() As String
            Get
                Return ResourceManager.GetString("strNoFilterData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please enter the Surname! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strNoFirstName() As String
            Get
                Return ResourceManager.GetString("strNoFirstName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please enter the last name! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strNoLastName() As String
            Get
                Return ResourceManager.GetString("strNoLastName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please choose a street! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strNoStreetSelected() As String
            Get
                Return ResourceManager.GetString("strNoStreetSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nothing selected for deletion ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strNothingSelectedDelete() As String
            Get
                Return ResourceManager.GetString("strNothingSelectedDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please choose a zip-code! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strNoZIPSelected() As String
            Get
                Return ResourceManager.GetString("strNoZIPSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die of ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strOF() As String
            Get
                Return ResourceManager.GetString("strOF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please enter the organization you are working for ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strOrgMissing() As String
            Get
                Return ResourceManager.GetString("strOrgMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Only the first page is shown in the preview, but all selected districts will be printed! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strPreview() As String
            Get
                Return ResourceManager.GetString("strPreview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Can not find the printer &apos;Microsoft Print to PDF&apos;. Make sure this printer is installed! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strPrinterFailure() As String
            Get
                Return ResourceManager.GetString("strPrinterFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die recipient list  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strRecipientList() As String
            Get
                Return ResourceManager.GetString("strRecipientList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You have not entered any roundsmen yet ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strRoundsemnMissing() As String
            Get
                Return ResourceManager.GetString("strRoundsemnMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  Roundsman:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strRoundsman() As String
            Get
                Return ResourceManager.GetString("strRoundsman", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name of the selected roundsman is NULL. Please change this before printing. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strRoundsmanNull() As String
            Get
                Return ResourceManager.GetString("strRoundsmanNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die addressees in  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strStreetCount() As String
            Get
                Return ResourceManager.GetString("strStreetCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Streets in database:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strStreetsInDatabase() As String
            Get
                Return ResourceManager.GetString("strStreetsInDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Success! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strSuccess() As String
            Get
                Return ResourceManager.GetString("strSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die There are  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strThereAre() As String
            Get
                Return ResourceManager.GetString("strThereAre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Total addressees:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strTotal() As String
            Get
                Return ResourceManager.GetString("strTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please enter the time in seconds the program shall wait ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strWaitInput() As String
            Get
                Return ResourceManager.GetString("strWaitInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property titCaution() As String
            Get
                Return ResourceManager.GetString("titCaution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property titError() As String
            Get
                Return ResourceManager.GetString("titError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property titInformation() As String
            Get
                Return ResourceManager.GetString("titInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Success ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property titSuccess() As String
            Get
                Return ResourceManager.GetString("titSuccess", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
